flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.1.0.0
- fast-logger-2.4.10
- hspec-2.4.1
- hspec-core-2.4.1
- hspec-discover-2.4.1
- hspec-expectations-0.8.2
- http-api-data-0.3.5
- natural-transformation-0.4
- newtype-generics-0.5
- servant-0.10
- servant-docs-0.10
- servant-server-0.10
- warp-3.2.11
resolver: lts-7.18
