flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.1.0.0
- derive-2.5.26
- haskell-src-exts-1.17.1
- mustache-2.1.2
- primitive-0.6.2.0
- servant-0.10
- servant-docs-0.10
- servant-server-0.10
- vector-0.12.0.0
resolver: lts-8.0
